- name: Install Dendrite
  hosts: all
  tasks:
    - name: Install Go
      ansible.builtin.apt:
        name: golang
        install_recommends: no
    - name: Clone Dendrite
      ansible.builtin.git: 
        repo: 'https://github.com/matrix-org/dendrite'
        dest: "{{ install_dir }}"
    - name: Create Dendrite config
      ansible.builtin.template:
        src: ./templates/monolith.yaml
        dest: "{{ install_dir }}/dendrite.yaml"
    - name: Build Dendrite
      ansible.builtin.command: ./build.sh
      args:
        chdir: "{{ install_dir }}"
    - name: Check if federation keys exist
      ansible.builtin.stat:
        path: "{{ install_dir }}/matrix_key.pem"
      register: key
    - name: Generate federation keys
      ansible.builtin.command: ./bin/generate-keys --private-key matrix_key.pem
      args:
        chdir: "{{ install_dir }}"
      when: key.stat.isreg is not defined
    - name: Add Dendrite service
      ansible.builtin.template:
        src: ./templates/monolith.sh
        dest: ~/.config/boot-scripts/dendrite.sh
