all:
  hosts:
    boop:
      server_name: dendrite1.veryme.ga
      well_known_server_name: dendrite1.veryme.ga
      disable_federation: false
      registration_disabled: false
      guests_disabled: true
    phone2:
      server_name: dendrite2.veryme.ga
      well_known_server_name: dendrite2.veryme.ga
      disable_federation: false
      registration_disabled: true
      guests_disabled: true
      install_dir: ~/dendrite-dir
  vars:
    install_dir: ~/dendrite
